version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/app1.sh
    - location: scripts/app2.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: root
